export const rankingSource =
  "https://www.restaurantbusinessonline.com/top-500-2025-ranking";

export const restaurantSources = [
  {
    id: "mcdonalds",
    rank: 1,
    name: "McDonald's",
    category: "Burger",
    domain: "mcdonalds.com",
    menuUrls: ["https://www.mcdonalds.com/us/en-us/full-menu.html"],
    allergenUrls: [
      "https://www.mcdonalds.com/us/en-us/about-our-food/nutrition-calculator.html",
    ],
  },
  {
    id: "starbucks",
    rank: 2,
    name: "Starbucks",
    category: "Snack",
    domain: "starbucks.com",
    menuUrls: ["https://www.starbucks.com/menu"],
    allergenUrls: ["https://www.starbucks.com/menu/nutrition/"],
  },
  {
    id: "chick-fil-a",
    rank: 3,
    name: "Chick-fil-A",
    category: "Chicken",
    domain: "chick-fil-a.com",
    menuUrls: ["https://www.chick-fil-a.com/menu"],
    allergenUrls: ["https://www.chick-fil-a.com/nutrition-allergens"],
  },
  {
    id: "taco-bell",
    rank: 4,
    name: "Taco Bell",
    category: "Tex-Mex",
    domain: "tacobell.com",
    menuUrls: ["https://www.tacobell.com/food"],
    allergenUrls: ["https://www.tacobell.com/nutrition/allergen-info"],
  },
  {
    id: "wendys",
    rank: 5,
    name: "Wendy's",
    category: "Burger",
    domain: "wendys.com",
    menuUrls: ["https://www.wendys.com/menu"],
    allergenUrls: ["https://www.wendys.com/nutrition-allergens"],
  },
  {
    id: "dunkin",
    rank: 6,
    name: "Dunkin'",
    category: "Snack",
    domain: "dunkindonuts.com",
    menuUrls: ["https://www.dunkindonuts.com/en/menu"],
    allergenUrls: ["https://www.dunkindonuts.com/en/menu/nutrition"],
  },
  {
    id: "chipotle",
    rank: 7,
    name: "Chipotle",
    category: "Mexican Grill",
    domain: "chipotle.com",
    menuUrls: ["https://www.chipotle.com/nutrition-calculator"],
    allergenUrls: ["https://www.chipotle.com/allergens"],
  },
  {
    id: "burger-king",
    rank: 8,
    name: "Burger King",
    category: "Burger",
    domain: "bk.com",
    menuUrls: ["https://www.bk.com/menu"],
    allergenUrls: ["https://www.bk.com/nutrition-explorer"],
  },
  {
    id: "subway",
    rank: 9,
    name: "Subway",
    category: "Sandwich",
    domain: "subway.com",
    menuUrls: ["https://www.subway.com/en-us/menunutrition/menu"],
    allergenUrls: [
      "https://www.subway.com/en-US/new-allergens",
      "https://www.subway.com/-/media/USA/Documents/Nutrition/US_Allergen_chart.pdf",
      "https://www.subway.com/en-us/menunutrition/nutrition",
    ],
  },
  {
    id: "dominos",
    rank: 10,
    name: "Domino's",
    category: "Pizza",
    domain: "dominos.com",
    menuUrls: ["https://www.dominos.com/en/pages/order/menu"],
    allergenUrls: [
      "https://www.dominos.com/en/pages/content/nutritional/allergen-info",
      "https://cache.dominos.com/olo/6_168_0/assets/build/market/US/_en/xml/allergens.xml",
    ],
  },
  {
    id: "panda-express",
    rank: 11,
    name: "Panda Express",
    category: "Chinese",
    domain: "pandaexpress.com",
    menuUrls: ["https://www.pandaexpress.com/menu"],
    allergenUrls: [
      "https://www.pandaexpress.com/nutritioninformation",
      "https://s3.amazonaws.com/PandaExpressWebsite/files/Nutrition.pdf",
    ],
  },
  {
    id: "panera",
    rank: 12,
    name: "Panera",
    category: "Sandwich",
    domain: "panerabread.com",
    menuUrls: ["https://www.panerabread.com/en-us/menu.html"],
    allergenUrls: [
      "https://www.panerabread.com/en-us/menu/nutritious-eating/allergen-and-nutrition-information.html",
    ],
  },
  {
    id: "popeyes",
    rank: 13,
    name: "Popeyes",
    category: "Chicken",
    domain: "popeyes.com",
    menuUrls: ["https://www.popeyes.com/menu"],
    allergenUrls: ["https://www.popeyes.com/nutrition"],
  },
  {
    id: "pizza-hut",
    rank: 14,
    name: "Pizza Hut",
    category: "Pizza",
    domain: "pizzahut.com",
    menuUrls: ["https://www.pizzahut.com/c/content/pizzas"],
    allergenUrls: ["https://www.pizzahut.com/c/content/nutrition"],
  },
  {
    id: "sonic",
    rank: 16,
    name: "Sonic Drive-In",
    category: "Burger",
    domain: "sonicdrivein.com",
    menuUrls: ["https://www.sonicdrivein.com/menu/"],
    allergenUrls: ["https://www.sonicdrivein.com/nutrition-allergen/"],
  },
  {
    id: "raising-canes",
    rank: 18,
    name: "Raising Cane's",
    category: "Chicken",
    domain: "raisingcanes.com",
    menuUrls: ["https://raisingcanes.com/menu/"],
    allergenUrls: [
      "https://raisingcanes.com/allergens/",
      "https://raisingcanes.cdn.prismic.io/raisingcanes/aHquuUMqNJQqIHQh_35074AllergenNutritionInfo_ALL_ENGLISH_DIGITAL.pdf",
    ],
  },
  {
    id: "dairy-queen",
    rank: 19,
    name: "Dairy Queen",
    category: "Burger",
    domain: "dairyqueen.com",
    menuUrls: ["https://www.dairyqueen.com/en-us/menu/"],
    allergenUrls: ["https://www.dairyqueen.com/en-us/nutrition/food-treats/"],
  },
  {
    id: "kfc",
    rank: 20,
    name: "KFC",
    category: "Chicken",
    domain: "kfc.com",
    menuUrls: ["https://www.kfc.com/menu"],
    allergenUrls: ["https://www.kfc.com/nutrition"],
  },
  {
    id: "wingstop",
    rank: 24,
    name: "Wingstop",
    category: "Chicken",
    domain: "wingstop.com",
    menuUrls: ["https://www.wingstop.com/menu"],
    allergenUrls: [
      "https://www.wingstop.com/allergens",
      "https://cdn.bfldr.com/NDQASMJ1/as/2v4qqb9ww8mvcm64gnh7ktnc/WS_Allergens_1226_2",
    ],
  },
  {
    id: "jack-in-the-box",
    rank: 23,
    name: "Jack in the Box",
    category: "Burger",
    domain: "jackinthebox.com",
    menuUrls: ["https://www.jackinthebox.com/menu"],
    allergenUrls: [
      "https://s3.amazonaws.com/static.jackinthebox.com/pdfs/allergens_reference_guide.pdf",
    ],
  },
  {
    id: "arbys",
    rank: 25,
    name: "Arby's",
    category: "Sandwich",
    domain: "arbys.com",
    menuUrls: ["https://www.arbys.com/menu/"],
    allergenUrls: ["https://www.arbys.com/nutrition/"],
  },
  {
    id: "whataburger",
    rank: 26,
    name: "Whataburger",
    category: "Burger",
    domain: "whataburger.com",
    menuUrls: ["https://whataburger.com/menu"],
    allergenUrls: ["https://whataburger.com/nutrition"],
  },
  {
    id: "papa-johns",
    rank: 31,
    name: "Papa Johns",
    category: "Pizza",
    domain: "papajohns.com",
    menuUrls: ["https://www.papajohns.com/order/menu"],
    allergenUrls: [
      "https://www.papajohns.com/allergens/papa-johns-allergen-guide.html",
      "https://www.papajohns.com/company/nutrition-allergen-information.html",
      "https://www.papajohns.com/company/papa-johns-ingredients.html",
    ],
  },
  {
    id: "jersey-mikes",
    rank: 30,
    name: "Jersey Mike's",
    category: "Sandwich",
    domain: "jerseymikes.com",
    menuUrls: ["https://www.jerseymikes.com/menu"],
    allergenUrls: ["https://www.jerseymikes.com/menu/nutrition"],
  },
  {
    id: "culvers",
    rank: 29,
    name: "Culver's",
    category: "Burger",
    domain: "culvers.com",
    menuUrls: ["https://www.culvers.com/menu-and-nutrition"],
    allergenUrls: [
      "https://www.culvers.com/nutrition-and-allergen-guide",
      "https://www.culvers.com/menu-and-nutrition",
    ],
  },
  {
    id: "little-caesars",
    rank: 22,
    name: "Little Caesars",
    category: "Pizza",
    domain: "littlecaesars.com",
    menuUrls: ["https://littlecaesars.com/en-us/menu/"],
    allergenUrls: [
      "https://littlecaesars.com/en-us/nutrition/",
      "https://littlecaesars.com/static/usnutritionguide.pdf",
    ],
  },
  {
    id: "zaxbys",
    rank: 39,
    name: "Zaxby's",
    category: "Chicken",
    domain: "zaxbys.com",
    menuUrls: ["https://www.zaxbys.com/menu/"],
    allergenUrls: [
      "https://www.zaxbys.com/uploads/ZAX_NAI_Guide_Digital_fe50d02b2b.pdf",
    ],
  },
  {
    id: "jimmy-johns",
    rank: 38,
    name: "Jimmy John's",
    category: "Sandwich",
    domain: "jimmyjohns.com",
    menuUrls: ["https://www.jimmyjohns.com/menu/"],
    allergenUrls: ["https://www.jimmyjohns.com/menu/nutrition/"],
  },
  {
    id: "five-guys",
    rank: 41,
    name: "Five Guys",
    category: "Burger",
    domain: "fiveguys.com",
    menuUrls: ["https://www.fiveguys.com/menu/"],
    allergenUrls: [
      "https://www.fiveguys.com/-/media/public-site/files/allergen-ingredients-and-nutrition-info/five-guys-us-nutrition--allergen-guide-english.pdf",
    ],
  },
  {
    id: "in-n-out",
    rank: 40,
    name: "In-N-Out Burger",
    category: "Burger",
    domain: "in-n-out.com",
    menuUrls: ["https://www.in-n-out.com/menu"],
    allergenUrls: [
      "https://www.in-n-out.com/menu/nutrition-info",
      "https://www.in-n-out.com/docs/default-source/downloads/in-n-out_allergen_info.pdf",
    ],
  },
  {
    id: "texas-roadhouse",
    rank: 15,
    name: "Texas Roadhouse",
    category: "Steakhouse",
    domain: "texasroadhouse.com",
    menuUrls: ["https://www.texasroadhouse.com/menu"],
    allergenUrls: ["https://www.texasroadhouse.com/menu"],
  },
  {
    id: "chilis",
    rank: 21,
    name: "Chili's",
    category: "Casual Dining",
    domain: "chilis.com",
    menuUrls: ["https://www.chilis.com/menu"],
    allergenUrls: ["https://www.chilis.com/menu"],
  },
  {
    id: "olive-garden",
    rank: 17,
    name: "Olive Garden",
    category: "Italian",
    domain: "olivegarden.com",
    menuUrls: ["https://www.olivegarden.com/menu"],
    allergenUrls: ["https://media.olivegarden.com/images/site/pdf/allergen_guide.pdf"],
  },
  {
    id: "applebees",
    rank: 27,
    name: "Applebee's",
    category: "Casual Dining",
    domain: "applebees.com",
    menuUrls: ["https://www.applebees.com/en/menu"],
    allergenUrls: ["https://www.applebees.com/en/nutrition/interactive-menu"],
  },
  {
    id: "ihop",
    rank: 32,
    name: "IHOP",
    category: "Breakfast",
    domain: "ihop.com",
    menuUrls: ["https://www.ihop.com/en/menu"],
    allergenUrls: ["https://www.ihop.com/en/nutrition/calculator"],
  },
  {
    id: "outback-steakhouse",
    rank: 35,
    name: "Outback Steakhouse",
    category: "Steakhouse",
    domain: "outback.com",
    menuUrls: ["https://www.outback.com/menu"],
    allergenUrls: ["https://www.outback.com/nutrition/smart-dining"],
  },
  {
    id: "longhorn-steakhouse",
    rank: 33,
    name: "LongHorn Steakhouse",
    category: "Steakhouse",
    domain: "longhornsteakhouse.com",
    menuUrls: ["https://www.longhornsteakhouse.com/menu"],
    allergenUrls: ["https://media.longhornsteakhouse.com/en_us/pdf/longhorn_allergen_guide.pdf"],
  },
  {
    id: "dennys",
    rank: 37,
    name: "Denny's",
    category: "Diner",
    domain: "dennys.com",
    menuUrls: ["https://www.dennys.com/menu"],
    allergenUrls: ["https://www.dennys.com/sites/default/files/2023-05/Mar23_AllergenGuide.pdf"],
  },
  {
    id: "cracker-barrel",
    rank: 34,
    name: "Cracker Barrel",
    category: "Casual Dining",
    domain: "crackerbarrel.com",
    menuUrls: ["https://www.crackerbarrel.com/menu"],
    allergenUrls: [
      "https://www.crackerbarrel.com/nutrition",
      "https://www.crackerbarrel.com/-/media/Project/cb-brandsite/brandsite/pdfs/AllergenGuide.pdf?rev=97fefa46ae7a471a841eecba92680873&hash=DA3EAE0E49A85081F186ED3F5F2049DF",
    ],
  },
  {
    id: "buffalo-wild-wings",
    rank: 28,
    name: "Buffalo Wild Wings",
    category: "Sports Bar",
    domain: "buffalowildwings.com",
    menuUrls: ["https://www.buffalowildwings.com/menu/"],
    allergenUrls: [
      "https://www.buffalowildwings.com/nutrition/",
      "https://assets.ctfassets.net/6dxmiqksdkqb/4y9m83FxBZmH5r1InmlOJ9/114d841feb46ae9671b6636bb15f5a34/BWW_Allergen___Preparation_Guide__05-20-2026_-_08-18-2026_.pdf",
      "https://assets.ctfassets.net/l5fkpck1mwg3/3Jqr0iVH00vyKpoLiRT2Fu/56fac8e76fa12354ec5c4bfb49ff8b81/Buffalo_Wild_Wings_-_Food_Menu_Ingredient_Statement.pdf",
    ],
  },
  {
    id: "red-lobster",
    rank: 45,
    name: "Red Lobster",
    category: "Seafood",
    domain: "redlobster.com",
    menuUrls: ["https://www.redlobster.com/menu"],
    allergenUrls: [
      "https://www.redlobster.com/nutrition/",
      "https://img-ecomm-rl-prod-fye5gqbxdtbghqer.a03.azurefd.net/brandsite/documents/US_Allergen_Final_Guide_4-20-26.pdf",
      "https://img-ecomm-rl-prod-fye5gqbxdtbghqer.a03.azurefd.net/brandsite/documents/US_Nutrition_4-20-26.pdf",
    ],
  },
  {
    id: "cheesecake-factory",
    rank: 36,
    name: "The Cheesecake Factory",
    category: "Casual Dining",
    domain: "thecheesecakefactory.com",
    menuUrls: ["https://www.thecheesecakefactory.com/menu"],
    allergenUrls: ["https://www.thecheesecakefactory.com/location/index/menu"],
  },
  {
    id: "waffle-house",
    rank: 50,
    name: "Waffle House",
    category: "Breakfast",
    domain: "wafflehouse.com",
    menuUrls: ["https://www.wafflehouse.com/menu/"],
    allergenUrls: ["https://www.wafflehouse.com/nutrition/"],
  },
  {
    id: "first-watch",
    rank: 55,
    name: "First Watch",
    category: "Breakfast",
    domain: "firstwatch.com",
    menuUrls: ["https://www.firstwatch.com/menu/"],
    allergenUrls: ["https://firstwatch.com/nutrition-and-allergens"],
  },
  {
    id: "red-robin",
    rank: 48,
    name: "Red Robin",
    category: "Burger",
    domain: "redrobin.com",
    menuUrls: ["https://www.redrobin.com/menu"],
    allergenUrls: ["https://www.redrobin.com/allergen-menu"],
  },
  {
    id: "bojangles",
    rank: 42,
    name: "Bojangles",
    category: "Chicken",
    domain: "bojangles.com",
    menuUrls: ["https://www.bojangles.com/menu/"],
    allergenUrls: ["https://www.bojangles.com/menu/nutrition/"],
    apiUrls: ["https://www.nutritionix.com/bojangles/nutrition-calculator"],
  },
  {
    id: "hardees",
    rank: 43,
    name: "Hardee's",
    category: "Burger",
    domain: "hardees.com",
    menuUrls: ["https://www.hardees.com/menu/"],
    allergenUrls: [
      "https://www.hardees.com/nutritional-info",
      "https://www.hardees.com/getmedia/c2d6e72d-8d95-4de2-915b-56e5d77b2329/nutritional-values-2025.pdf",
    ],
    apiUrls: ["https://www.nutritionix.com/hardees/nutrition-calculator"],
  },
  {
    id: "dutch-bros",
    rank: 44,
    name: "Dutch Bros Coffee",
    category: "Coffee",
    domain: "dutchbros.com",
    menuUrls: ["https://www.dutchbros.com/menu"],
    allergenUrls: ["https://www.dutchbros.com/menu/nutrition-info-seasonal"],
  },
  {
    id: "golden-corral",
    rank: 46,
    name: "Golden Corral",
    category: "Buffet",
    domain: "goldencorral.com",
    menuUrls: ["https://www.goldencorral.com/menu/"],
    allergenUrls: [
      "https://www.goldencorral.com/menu/",
      "https://www.goldencorral.com/nutrition/nutrition-allergen-statement/",
    ],
  },
  {
    id: "carls-jr",
    rank: 47,
    name: "Carl's Jr.",
    category: "Burger",
    domain: "carlsjr.com",
    menuUrls: ["https://www.carlsjr.com/menu"],
    allergenUrls: [
      "https://www.carlsjr.com/nutritional-info",
      "https://www.carlsjr.com/getContentAsset/cccf694a-3d94-4cbc-adfc-28c255939f92/dfc3d011-8f63-43f6-9ed8-4b444333a1d0/nutritional-info.pdf?language=en-US",
    ],
  },
  {
    id: "tropical-smoothie-cafe",
    rank: 49,
    name: "Tropical Smoothie Cafe",
    category: "Smoothie",
    domain: "tropicalsmoothiecafe.com",
    menuUrls: ["https://www.tropicalsmoothiecafe.com/menu/"],
    allergenUrls: [
      "https://www.tropicalsmoothiecafe.com/nutrition/",
      "https://www.tropicalsmoothiecafe.com/nutrition/latest",
    ],
  },
  {
    id: "bjs-restaurant",
    rank: 51,
    name: "BJ's Restaurant & Brewhouse",
    category: "Casual Dining",
    domain: "bjsrestaurants.com",
    menuUrls: ["https://www.bjsrestaurants.com/menu"],
    allergenUrls: [
      "https://www.bjsrestaurants.com/marketing-pages/allergen-and-nutritional-guides",
      "https://bjsrestaurants.scene7.com/is/content/bjsrestaurants/0426_BJS_GLUTEN_ALLERGENpdf",
      "https://bjsrestaurants.scene7.com/is/content/bjsrestaurants/0426_BJS_NUTRIpdf",
    ],
  },
  {
    id: "shake-shack",
    rank: 52,
    name: "Shake Shack",
    category: "Burger",
    domain: "shakeshack.com",
    menuUrls: ["https://shakeshack.com/menu"],
    allergenUrls: [
      "https://shakeshack.com/nutrition-allergens",
      "https://shakeshack.com/sites/default/files/2026-01/_Master%20Nut%20%26%20Allergen%201.6.26.pdf",
    ],
    apiUrls: ["https://www.nutritionix.com/shake-shack/nutrition-calculator"],
  },
  {
    id: "crumbl",
    rank: 53,
    name: "Crumbl",
    category: "Bakery",
    domain: "crumblcookies.com",
    menuUrls: ["https://crumblcookies.com/menu"],
    allergenUrls: ["https://crumblcookies.com/nutrition/regular"],
    apiUrls: ["https://www.nutritionix.com/crumbl-cookies/nutrition-calculator"],
  },
  {
    id: "qdoba",
    rank: 54,
    name: "Qdoba Mexican Eats",
    category: "Mexican Grill",
    domain: "qdoba.com",
    menuUrls: ["https://www.qdoba.com/menu"],
    allergenUrls: [
      "https://www.qdoba.com/nutrition",
      "https://www.qdoba.com/public/assets/documents/qdoba-allergen-information.pdf",
    ],
  },
  {
    id: "firehouse-subs",
    rank: 56,
    name: "Firehouse Subs",
    category: "Sandwich",
    domain: "firehousesubs.com",
    menuUrls: ["https://www.firehousesubs.com/menu/"],
    allergenUrls: [
      "https://www.firehousesubs.com/nutrition/",
      "https://www.firehousesubs.com/pdf/NUTRITIONAL_Information_Allergen.pdf",
    ],
  },
  {
    id: "el-pollo-loco",
    rank: 57,
    name: "El Pollo Loco",
    category: "Chicken",
    domain: "elpolloloco.com",
    menuUrls: ["https://www.elpolloloco.com/menu"],
    allergenUrls: [
      "https://www.elpolloloco.com/nutrition",
      "https://www.elpolloloco.com/content/pdfs/epl_web_nutrition_guide_mod_1_2025_hr.pdf",
    ],
  },
  {
    id: "marcos-pizza",
    rank: 58,
    name: "Marco's Pizza",
    category: "Pizza",
    domain: "marcos.com",
    menuUrls: ["https://www.marcos.com/our-menu"],
    allergenUrls: [
      "https://www.marcos.com/faq/",
      "https://www.nutritionix.com/marcos-pizza/portal",
    ],
  },
  {
    id: "mcalisters-deli",
    rank: 59,
    name: "McAlister's Deli",
    category: "Sandwich",
    domain: "mcalistersdeli.com",
    menuUrls: ["https://www.mcalistersdeli.com/menu"],
    allergenUrls: ["https://www.mcalistersdeli.com/nutrition/allergen-menu"],
  },
  {
    id: "freddys",
    rank: 60,
    name: "Freddy's Frozen Custard & Steakburgers",
    category: "Burger",
    domain: "freddys.com",
    menuUrls: ["https://www.freddys.com/menu"],
    allergenUrls: ["https://www.freddys.com/nutrition-and-allergens"],
  },
  {
    id: "pf-changs",
    rank: 61,
    name: "P.F. Chang's",
    category: "Asian",
    domain: "pfchangs.com",
    menuUrls: ["https://www.pfchangs.com/menu"],
    allergenUrls: ["https://www.pfchangs.com/nutrition/allergens-to-go"],
  },
  {
    id: "del-taco",
    rank: 62,
    name: "Del Taco",
    category: "Tex-Mex",
    domain: "deltaco.com",
    menuUrls: ["https://deltaco.com/menu"],
    allergenUrls: [
      "https://deltaco.com/nutrition.html",
      "https://deltaco.com/files/pdf/2026/allergens-06-2026.pdf",
    ],
  },
  {
    id: "cava",
    rank: 63,
    name: "CAVA",
    category: "Mediterranean",
    domain: "cava.com",
    menuUrls: ["https://cava.com/menu"],
    allergenUrls: [
      "https://cava.com/nutrition",
      "https://assets.ctfassets.net/kugm9fp9ib18/7KrOGNUFZjBddOWezWLWwm/a20b10d71b9b0496f96b8e38bd8e0211/CAVA-REC-GID-0326-AllergReg.pdf",
    ],
  },
  {
    id: "nothing-bundt-cakes",
    rank: 64,
    name: "Nothing Bundt Cakes",
    category: "Bakery",
    domain: "nothingbundtcakes.com",
    menuUrls: ["https://www.nothingbundtcakes.com/all-products/"],
    allergenUrls: [
      "https://www.nothingbundtcakes.com/nutrition/",
      "https://www.nothingbundtcakes.com/nutrition/ingredients/?bakery=undefined",
    ],
  },
  {
    id: "yard-house",
    rank: 65,
    name: "Yard House",
    category: "Casual Dining",
    domain: "yardhouse.com",
    menuUrls: ["https://www.yardhouse.com/menu"],
    allergenUrls: [
      "https://www.yardhouse.com/nutrition",
      "https://media.yardhouse.com/en_us/pdf/Yard_House_Allergen_Guide.pdf",
      "https://media.yardhouse.com/en_us/pdf/Nutrition_Dietary_Allergen_Guide.pdf",
    ],
  },
  {
    id: "churchs-texas-chicken",
    rank: 66,
    name: "Church's Texas Chicken",
    category: "Chicken",
    domain: "churchs.com",
    menuUrls: ["https://www.churchs.com/menu/"],
    allergenUrls: [
      "https://www.churchs.com/nutrition/",
      "https://www.churchs.com/wp-content/uploads/2022/08/NutritionalFactSheet_ChurchsChicken_080922.pdf",
    ],
    apiUrls: ["https://mobile-api.churchs.com/api/v1/menu"],
  },
  {
    id: "ruths-chris",
    rank: 67,
    name: "Ruth's Chris Steak House",
    category: "Steakhouse",
    domain: "ruthschris.com",
    menuUrls: ["https://www.ruthschris.com/menu/"],
    allergenUrls: ["https://www.ruthschris.com/menu/"],
    apiUrls: ["https://www.nutritionix.com/ruths-chris-steak-house/nutrition-calculator"],
  },
  {
    id: "auntie-annes",
    rank: 68,
    name: "Auntie Anne's",
    category: "Snack",
    domain: "auntieannes.com",
    menuUrls: ["https://www.auntieannes.com/menu"],
    allergenUrls: [
      "https://www.auntieannes.com/nutrition",
      "https://assets.ctfassets.net/zqt8tllj2cy0/2jjVNaTNGDoMGd4QVucpSy/0f94c0d0541ec11a334dba7ce6fc56b0/Auntie-Annes-Nutrition-Guide.pdf",
      "https://auntieannes.com.mx/wp-content/uploads/2025/07/Food-Allergens-and-Sensitivities-Chart.pdf",
    ],
  },
  {
    id: "tim-hortons",
    rank: 69,
    name: "Tim Hortons",
    category: "Coffee",
    domain: "timhortons.com",
    menuUrls: ["https://www.timhortons.com/menu"],
    allergenUrls: [
      "https://www.timhortons.com/nutrition-and-allergens",
      "https://timhortons.com.pa/pdfs/TH-USA-Allergen-Guide-December-2022.pdf",
    ],
  },
  {
    id: "cheddars",
    rank: 70,
    name: "Cheddar's Scratch Kitchen",
    category: "Casual Dining",
    domain: "cheddars.com",
    menuUrls: ["https://www.cheddars.com/menu"],
    allergenUrls: [
      "https://m.cheddars.com/nutritional-info",
      "https://media.cheddars.com/images/site/pdf/Cheddars_Allergen_Guide.pdf",
      "https://media.cheddars.com/images/site/pdf/Cheddars_Nutrition_Guide.pdf",
    ],
  },
];
